# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set repo path
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV
      
      - name: Install Halium dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt-get install git gnupg flex bison gperf build-essential zip bzr curl libc6-dev libncurses5-dev:i386 x11proto-core-dev libx11-dev:i386 libreadline6-dev:i386 libgl1-mesa-glx:i386 libgl1-mesa-dev g++-multilib mingw-w64-i686-dev tofrodos python-markdown libxml2-utils xsltproc zlib1g-dev:i386 schedtool repo liblz4-tool bc lzop imagemagick libncurses5 rsync
      
      - name: Get Halium Source
        run: |
          mkdir $REPO_NAME/halium && cd $REPO_NAME/halium
          HALIUM_VER = cat $REPO_NAME/halium-ver
          repo init -u https://github.com/Halium/android -b $HALIUM_VER --depth=1
          repo sync -c -j 16
          
